### PR TITLE
Music command recognition

### PR DESCRIPTION
**Pull request by jonatep**
This code needs this pull request https://github.com/LuisMayo/ace-attorney-bot/pull/27 in order to work fully, as a new argument has been added in the function "comments_to_scene". 
When mentioning the bot, now you can add a music= argument, followed by 3 posibilities:
PWR: Just like the default bot, using music from the first game
JFA: Music from Justice for All
TAT: Music from Trials and Tribulations
If there is no music argument in the mention, it will be selected randomly between these options. However, if there is some typo in the arguments, the bot will remind the user how to write it properly
I'm sure this isn't perfect, so please tell me any mistakes I may have made :)

PD: The other person commiting this, "Julian", is also me, I forgot to configure the git user name and I don't know how to change it :P

### CODE REVIEW

**Comment by jonatep** [comment]
I don't know if I should be the one resolving these conflicts that have appeared when commiting this pr, or if the author is the only one to do so

**Comment by LuisMayo** [comment]
We both can!

I can do it in the merge commit and you can do a rebase on top of current main commit

Doing a rebase is a bit more of a hassle than the merge commit so if you're kind of new to fit just leave the conflicts to me :)

Thanks for your work!

**Comment by jonatep** [comment]
Okay, it's good to know! Yep, I'm kind of new in GitHub so if it isn't much of an issue for you I would appreciate if you could handle the conflicts :)

**Review by LuisMayo — CHANGES_REQUESTED** [review]
Hi!
After a review of the changes I think I'd need the following changes if you may accept to make them

- [ ] Make "Phoenix Wright: Ace Attorney" the default if no soundtrack is selected. This is something I personally prefer but I won't manage this bot only on my preferences. However, [a poll conducted with the bot users](https://twitter.com/aceCourtBot/status/1371394882833616898?s=19) shows that the majority prefer it that way too

- [ ] Add a Random option. I actually like the idea of letting the universe decide for us, so I think that maybe if the user specifies music=rnd, then the soundtrack could be chosen at random

- [ ] Currently the way you're parsing the user input may lead to future errors if more user-provided options are to be introduced. You should either split by "music=" instead of by "=" (if that's possible I don't know) or use regular expressions. If you're having too much trouble with this one please not worry and I'll gladly do it :3

Again I cannot thank you enough your contribution ^^.

**Comment by jonatep** [comment]
All done! It should still work without major issues. Thanks a lot for the feedback, glad to help! :)

**Review by LuisMayo — APPROVED** [review]

**Comment by LuisMayo** [comment]
Done now!
Thanks for your work

**Comment by jonatep** [comment]
Perfect! It was nothing, I hope everyone likes it :)

**Pull request merged**
